version: "3.9"
services:

  mcp-server:
  # o build: . busca o dockerfile na raiz do projeto, onde está o código do mcp-server
    build: . 
    container_name: filazero-mcp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CACHE_TTL_COMPANIES=300
    stdin_open: true # para mcp STDIO
    tty: true #mantém o processo iterativo aberto



