version: "3.9"
services:

  mcp-server:
  # o build: . busca o dockerfile na raiz do projeto, onde está o código do mcp-server
    build: . 
    image: residencia3-squad10-mcp
    container_name: filazero-mcp
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CACHE_TTL_COMPANIES=300
       - FILAZERO_API_URL=https://api.staging.filazero.net 
    stdin_open: true # para mcp STDIO
    tty: true #mantém o processo iterativo aberto



